# Generated by Django 4.0.6 on 2022-08-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_cart_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Edition',
            new_name='Stock',
        ),
    ]
